# Generated by Django 5.0.6 on 2024-08-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdata_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='country',
        ),
    ]
