# Generated by Django 5.0.6 on 2024-08-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userdata_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
