# Generated by Django 5.0.6 on 2024-09-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdata_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
