# Generated by Django 5.0.6 on 2024-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userdata_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
