# Generated by Django 5.0.6 on 2024-08-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
