# Generated by Django 5.0.6 on 2024-08-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_carousel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.FileField(help_text='Image size must be 1920 X 1080 pixels', max_length=60, upload_to='products/'),
        ),
    ]
