# Generated by Django 5.0.6 on 2024-08-06 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('sub_title', models.TextField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('price_that_you_sell', models.IntegerField(help_text='the price that you sell', null=True)),
                ('Orignal_price', models.IntegerField(help_text='this price is to attract the costumer and this is higher than price that you sell', null=True)),
                ('More_information', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('----', '----'), ('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], default='----', max_length=20, null=True)),
                ('image', models.FileField(help_text='Image size must be 500 X 500 pixels', null=True, upload_to='products/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
