# Generated by Django 5.0.6 on 2024-08-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels', null=True, upload_to='products/'),
        ),
    ]
