# Generated by Django 5.0.6 on 2024-08-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_products_image2_products_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.FileField(blank=True, help_text='Image size must be 500 X 500 pixels', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.FileField(blank=True, help_text='Image size must be 500 X 500 pixels', null=True, upload_to='products/'),
        ),
    ]
