# Generated by Django 5.0.6 on 2024-08-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_products_slug_alter_products_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
