# Generated by Django 5.0.6 on 2024-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_products_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels and add all images. If you dont have enough images then you can add 1 image 6 times', max_length=200, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image5',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels and add all images. If you dont have enough images then you can add 1 image 6 times', max_length=200, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image6',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels and add all images. If you dont have enough images then you can add 1 image 6 times', max_length=200, null=True, upload_to='products/'),
        ),
    ]
