# Generated by Django 5.0.6 on 2024-08-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_rename_title_products_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price_that_you_sell',
            new_name='price',
        ),
    ]
