# Generated by Django 5.0.6 on 2024-08-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_products_slug'),
        ('Product', '0010_rename_price_that_you_sell_products_price'),
    ]

    operations = [
    ]
