# Generated by Django 5.0.6 on 2024-08-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_merge_20240813_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='availability',
        ),
    ]
