# Generated by Django 5.0.6 on 2024-08-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_remove_products_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='availability',
            field=models.CharField(choices=[('----', '----'), ('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], default='----', max_length=20, null=True),
        ),
    ]
