# Generated by Django 5.0.6 on 2024-08-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_products_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Orignal_price',
        ),
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.IntegerField(blank=True, help_text='this price is to attract the costumer and this is higher than price that you sell', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='shipping_charges',
            field=models.IntegerField(null=True),
        ),
    ]
