# Generated by Django 5.0.6 on 2024-08-28 06:31

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_remove_products_orignal_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels and add all images. If you dont have enough images then you can add 1 image 6 times', max_length=200, null=True, upload_to='products/', validators=[Product.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='products',
            name='image2',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels and add all images. If you dont have enough images then you can add 1 image 6 times', max_length=200, null=True, upload_to='products/', validators=[Product.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='products',
            name='image3',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels and add all images. If you dont have enough images then you can add 1 image 6 times', max_length=200, null=True, upload_to='products/', validators=[Product.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='products',
            name='image4',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels and add all images. If you dont have enough images then you can add 1 image 6 times', max_length=200, null=True, upload_to='products/', validators=[Product.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='products',
            name='image5',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels and add all images. If you dont have enough images then you can add 1 image 6 times', max_length=200, null=True, upload_to='products/', validators=[Product.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='products',
            name='image6',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels and add all images. If you dont have enough images then you can add 1 image 6 times', max_length=200, null=True, upload_to='products/', validators=[Product.models.validate_image_size]),
        ),
    ]
