# Generated by Django 5.0.6 on 2024-08-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_alter_products_image_alter_products_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='shipping_charges',
        ),
    ]
