# Generated by Django 5.0.6 on 2024-09-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_remove_products_shipping_charges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
