# Generated by Django 5.0.6 on 2024-09-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('----', '----'), ('x-smail', 'x-smail'), ('smail', 'smail'), ('medium', 'medium'), ('large', 'large'), ('x-large', 'x-large')], default='----', max_length=20, null=True),
        ),
    ]
