# Generated by Django 5.0.6 on 2024-09-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('----', '----'), ('x-small', 'x-small'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('x-large', 'x-large')], default='----', max_length=20, null=True),
        ),
    ]
