# Generated by Django 5.0.6 on 2024-09-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
