# Generated by Django 5.0.6 on 2024-09-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
