# Generated by Django 5.0.6 on 2024-09-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_newsletter_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='create',
            new_name='subscribed_at',
        ),
    ]
