# Generated by Django 5.0.6 on 2024-09-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_rename_create_newsletter_subscribed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='subscribed_at',
        ),
    ]
