# Generated by Django 5.0.6 on 2024-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usrinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('map_link', models.TextField()),
            ],
            options={
                'verbose_name': 'Admin info',
                'verbose_name_plural': "Admin info's",
            },
        ),
    ]
