# Generated by Django 5.0.6 on 2024-09-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_usrinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrinfo',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
