# Generated by Django 5.0.6 on 2024-09-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_usrinfo_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrinfo',
            name='email2',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='working_hours',
            field=models.TextField(null=True),
        ),
    ]
