# Generated by Django 5.0.6 on 2024-09-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_usrinfo_email2_usrinfo_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='working_hours',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
