# Generated by Django 5.0.6 on 2024-08-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0002_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
