# Generated by Django 5.0.6 on 2024-08-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header_footer', '0007_remove_footer_create_remove_footer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='name',
            field=models.CharField(help_text='Name Here', max_length=100),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.URLField(help_text='URL Here'),
        ),
    ]
