# Generated by Django 5.0.6 on 2024-08-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('pinterest', 'pinterest'), ('Youtube', 'Youtube')], default='facebook', max_length=100),
        ),
    ]
