# Generated by Django 5.0.6 on 2024-09-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_social_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Social Icon', 'verbose_name_plural': "Social Icon's"},
        ),
    ]
