# Generated by Django 5.0.6 on 2024-08-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='In_Stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='compare_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
