# Generated by Django 5.0.6 on 2024-08-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_in_stock_alter_products_compare_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_2',
            field=models.FileField(max_length=60, null=True, upload_to='products/'),
        ),
    ]
