# Generated by Django 5.0.6 on 2024-08-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_image_3_products_image_4_products_image_5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_6',
        ),
    ]
