# Generated by Django 5.0.6 on 2024-08-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0007_remove_products_image_2_remove_products_image_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='compare_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='Orignal_price',
            field=models.IntegerField(help_text='this price is to attract the costumer and this is higher than price that you sell', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price_that_you_sell',
            field=models.IntegerField(help_text='this price the price that you sell', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='More_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(max_length=60, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
