# Generated by Django 5.0.6 on 2024-08-04 10:29

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_products_image_2_remove_products_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '200x150', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
