# Generated by Django 5.0.6 on 2024-08-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cropping',
        ),
    ]
