# Generated by Django 5.0.6 on 2024-08-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_price_that_you_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(choices=[('choice', 'CHOICE'), ('in stock', 'IN STOCK'), ('out of stock', 'OUT OF STOCK')], default='choice', max_length=20, null=True),
        ),
    ]
