# Generated by Django 5.0.6 on 2024-08-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='color',
            new_name='availability',
        ),
    ]
