# Generated by Django 5.0.6 on 2024-08-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_color_products_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='In_Stock',
        ),
    ]
