# Generated by Django 5.0.6 on 2024-08-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_products_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_title',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
