# Generated by Django 5.0.6 on 2024-08-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_products_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_title',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
