# Generated by Django 5.0.6 on 2024-08-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_products_cropping'),
        ('products', '0015_alter_products_image_alter_products_sub_title'),
    ]

    operations = [
    ]
