# Generated by Django 5.0.6 on 2024-08-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_merge_20240805_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(help_text='Image size must be 500 X 500 pixels', null=True, upload_to='products/'),
        ),
    ]
